// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Machine struct {
	ID          int64
	Priority    int32
	Name        string
	Description string
	Generation  pgtype.Numeric
	Price       pgtype.Numeric
	Increment   pgtype.Numeric
	Type        string
}

type User struct {
	ID       int64
	Username string
	Password string
	Cash     pgtype.Numeric
	LastSave pgtype.Timestamptz
}

type UsersMachine struct {
	UserID    int64
	MachineID int64
	Level     pgtype.Int4
}
